version: '3'

services:

  workaszn_backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/workaszn
      - PORT=5000
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - workaszn_mongo
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules 

  workaszn_frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    depends_on:
      - workaszn_backend
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  workaszn_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
