version: '3'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/workaszn
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
